name: Deploy Java App to GCP VM

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Unit Tests
        run: mvn test

      - name: Build Project and Package JAR
        run: mvn package -DskipTests

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Google Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/java-app:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: SSH into GCP VM and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_SSH_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            sudo apt update -y
            sudo apt install -y docker.io
            gcloud auth configure-docker us-central1-docker.pkg.dev

            # Pull and Run Docker Image
            docker pull us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/java-app:latest
            docker stop java-app || true
            docker rm java-app || true
            docker run -d --name java-app -p 8080:8080 --env-file .env us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/java-app:latest
