jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: cicddemo-451910  # Replace with your Google Cloud project ID
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}  # Using the secret here

      # Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > /tmp/credentials.json
          gcloud auth activate-service-account --key-file=/tmp/credentials.json
          gcloud config set project cicddemo-451910  # Replace with your Google Cloud project ID

      # Checkout the repository's code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Run unit tests using Maven
      - name: Run unit test
        run: mvn test

      # Build the project using Maven
      - name: Build project and package jar
        run: mvn package -Dmaven.test.skip
